apiVersion: v1
kind: Service
metadata:
  name: {{ include "admission-webhook.fullname" . }}
  labels:
    {{- include "admission-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "admission-webhook.selectorLabels" . | nindent 4 }}
